# version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  pocketbase:
    image: mayankraj07/schemashield-pocketbase:latest
    volumes:
      - "./pb_data:/pb_data"
    ports:
      - "8090:8090"
    depends_on:
      redis:
        condition: service_healthy

  agent_pg:
    build:
      context: ../agent-pg
    env_file: .env
    depends_on:
      - redis
